version: '3.4'

services:
  aspintroduction:
    image: aspintroduction:dev
    container_name: AspIntroduction
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AspIntroduction"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/radoslavbogdanov/Downloads/DEVELOPMENT/C# WEB/ASP.NET Introduction/AspIntroduction/AspIntroduction:/app
      - /Users/radoslavbogdanov/Downloads/DEVELOPMENT/C# WEB/ASP.NET Introduction/AspIntroduction:/src
      - /Users/radoslavbogdanov/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/radoslavbogdanov/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/AspIntroduction.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true